### ISSUE TITLE
issue installing indigo

### ISSUE THREAD

**Issue by ebucholtz** [mcs07/homebrew-cheminformatics#17]
Setting up a new mac with homebrew-cheminformatics 

When I brew install indigo I get the following error:

==> Installing indigo from mcs07/cheminformatics
==> Installing dependencies for mcs07/cheminformatics/indigo: cmake
==> Installing mcs07/cheminformatics/indigo dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.7.1.el_capitan.bott
######################################################################## 100.0%
==> Pouring cmake-3.7.1.el_capitan.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.7.1: 2,143 files, 29M
==> Installing mcs07/cheminformatics/indigo 
==> Downloading https://github.com/epam/Indigo/archive/indigo-1.2.1.tar.gz
==> Downloading from https://codeload.github.com/epam/Indigo/tar.gz/indigo-1.2.1
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/mcs07/b9b2ccfdb9bc23f60044/ra
######################################################################## 100.0%
==> Downloading https://gist.githubusercontent.com/mcs07/541bcda4cfd6a7d8668b/ra
######################################################################## 100.0%
==> Patching
==> Applying indigo-el-capitan.diff
patching file common/cmake/GetSystemVersion.cmake
patch unexpectedly ends in middle of line
Hunk #1 succeeded at 27 with fuzz 1.
==> Applying indigo-depict-1.2.1.diff
patching file utils/indigo-depict/CMakeLists.txt
==> cmake ../build_scripts/indigo-all
==> make
Last 15 lines from /Users/ebucholtz/Library/Logs/Homebrew/indigo/02.make:
Scanning dependencies of target indigo-inchi-c-test-shared
[ 99%] Building C object indigo-inchi/indigo-inchi/CMakeFiles/indigo-inchi-c-test-shared.dir/tests/c/indigo-inchi-test.c.o
[ 99%] Building C object indigo/api/CMakeFiles/indigo-c-test-shared.dir/tests/c/indigo-test.c.o
[ 99%] Linking CXX executable ../../dist/Mac/10.11/lib/indigo-inchi-c-test-shared
[ 99%] Linking CXX executable ../../dist/Mac/10.11/lib/indigo-c-test-shared
[ 99%] Built target indigo-renderer-shared
Scanning dependencies of target indigo-renderer-c-test-shared
make[2]: *** No rule to make target `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/ApplicationServices.framework', needed by `dist/Mac/10.11/lib/indigo-renderer-c-test-shared'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 99%] Building C object indigo-renderer/renderer/CMakeFiles/indigo-renderer-c-test-shared.dir/tests/c/indigo-renderer-test.c.o
[ 99%] Built target indigo-c-test-shared
make[1]: *** [indigo-renderer/renderer/CMakeFiles/indigo-renderer-c-test-shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 99%] Built target indigo-inchi-c-test-shared
make: *** [all] Error 2

**Comment by mcs07** [comment]
Should hopefully work now
