### ISSUE TITLE
RDKit for python 2 and 3, both?

### ISSUE THREAD

**Issue by windemut** [mcs07/homebrew-cheminformatics#24]
In the description of the rdkit formula it says "RDKit can be built to work with either Python 2 or Python 3, but not both simultaneously". I use both Python 2 and 3 from time to time, and it would be nice to have to not switch installations all the time. Is this a hard and fast rule or might there be a way around it?

**Comment by mcs07** [comment]
For this I would recommend using anaconda python, so you can create conda environments with different python versions and `conda install rdkit` in each.

I don't believe it is possible to do a single cmake compile of RDKit (as homebrew does) and have it work with multiple python environments.

**Comment by windemut** [comment]
Ah, thank you, anaconda might work. I'll try it, or make do with 
switching once in a while.
