### ISSUE TITLE
Depreciated calls in Homebrew 1.5.10

### ISSUE THREAD

**Issue by chemdg** [mcs07/homebrew-cheminformatics#26]
Hi,
I'm receiving some warnings in homebrew about depreciated calls during `brew update`

> Warning: Calling 'depends_on :python' is deprecated!
> Use 'depends_on "python@2"' instead.
> /usr/local/Homebrew/Library/Taps/mcs07/homebrew-cheminformatics/Formula/indigo.rb:21:in `<class:Indigo>'
> Please report this to the mcs07/cheminformatics tap!
> 
> Warning: Calling 'depends_on :python3' is deprecated!
> Use 'depends_on "python"' instead.
> /usr/local/Homebrew/Library/Taps/mcs07/homebrew-cheminformatics/Formula/open-babel.rb:18:in `<class:OpenBabel>'
> Please report this to the mcs07/cheminformatics tap!
> 
> Warning: Calling 'depends_on :postgresql' is deprecated!
> Use 'depends_on "postgresql"' instead.
> /usr/local/Homebrew/Library/Taps/mcs07/homebrew-cheminformatics/Formula/rdkit.rb:32:in `<class:Rdkit>'
> Please report this to the mcs07/cheminformatics tap!

I think it has to do with some changes to the way homebrew handles the different python versions now.

Any help would be appreciated and let me know if you need any more information from me.

-David

**Comment by mcs07** [comment]
These should all be resolved, thanks for the heads up.
